### ISSUE TITLE
Automatically build and publish cflinuxfs4-compat BOSH release

### ISSUE THREAD

**Issue by robdimsdale** [cloudfoundry/cflinuxfs4-compat-release#1]
In order to confirm to [Cloud Foundry RFC #16](https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0016-python-and-ruby-removal-from-cf-stack.md) we need to automatically build and publish a version of cflinuxfs4 that continues to include ruby and python (AKA `cflinuxfs4-compat`).

The RFC contains more details, but in summary:

1. This repository is where the BOSH release of the stack should reside
2. The stack should automatically be published to bosh.io [here](https://bosh.io/releases/github.com/cloudfoundry/cflinuxfs4-compat-release?all=1). We don't have to publish it anywhere else (e.g. we don't have to publish it to GitHub releases on this repository).
3. We don't have to create build receipts - at least not at this time. It could be a potential future addition.
4. We should build and publish a new version of the stack every time there is a newly-published [release of cflinuxfs4](https://github.com/cloudfoundry/cflinuxfs4-release). It should have the same version as the upstream `cflinuxfs4` stack.
5. We do not want to trigger on new versions of ruby or python. We blindly include whatever the latest version of ruby/python packages are available.
6. We do not need to run CATS, or in fact any testing on this stack.
7. We have the flexibility to create this automation wherever is most convenient for us - GitHub actions or concourse are both fine.

**Comment by beyhan** [comment]
@robdimsdale do you have a rough estimation when the first version of this stack will be available?

**Comment by robdimsdale** [comment]
@beyhan sorry about the delay. We've been a little short-staffed recently (and likely will be for a few more weeks) but this is on our priority list. We haven't forgotten. We know this is important to the community.

**Comment by sophiewigmore** [comment]
Notes from meeting 5/31 with @brayanhenao 
- Add a compat stack list of packages to the cflinuxfs4/packages directory
- Add a workflow to the cflinuxfs4 repository that is triggered on a release, and creates a compat stack using the compat packages, with the same version as the regular release, and creates a bosh release in this repository

**Comment by sophiewigmore** [comment]
WIP https://github.com/cloudfoundry/cflinuxfs4/pull/7, still need to find some time to put the workflow together, hoping to get to this early next week.

**Comment by sophiewigmore** [comment]
@beyhan we are actively working on this, I believe a bosh release should be out next week

**Comment by sophiewigmore** [comment]
PR to create the release via GHA : https://github.com/cloudfoundry/cflinuxfs4-compat-release/pull/5

**Comment by beyhan** [comment]
@sophiewigmore thank you for the heads-up.

**Comment by sophiewigmore** [comment]
While there are releases on this repository, we are still testing the release process and release itself. I'll update this issue when we're more confident in the final result

**Comment by sophiewigmore** [comment]
- Smoke tests pass
- building an [NPM fixture](https://github.com/cloudfoundry/nodejs-buildpack/tree/master/fixtures/npm) with the new stack succeeds (both with the newest versions of the buildpack, and with an old version without  bootstrapped python)
- building a basic [PHP fixture](https://github.com/cloudfoundry/cf-acceptance-tests/tree/main/assets/php) with the new stack succeeds
- building a basic [ruby fixture](https://github.com/cloudfoundry/cf-acceptance-tests/tree/main/assets/ruby-simple) with the new stack succeeds (both with the newest versions of the buildpack, and with an old version without  bootstrapped ruby)

**Comment by sophiewigmore** [comment]
Workflow:
- [cflinuxfs4 workflow](https://github.com/cloudfoundry/cflinuxfs4/actions/workflows/create-compat-stack.yml) triggers a repo dispatch with the version when a release is cut to cflinuxfs4-compat-release
- [cflinuxfs4-compat-release workflow](https://github.com/cloudfoundry/cflinuxfs4-compat-release/actions/workflows/create-release.yml) receives dispatch with version information and takes the released cflinuxfs4 images and installs ruby, python, and related packages on top, and then creates the bosh release and releases it to Github

**Comment by sophiewigmore** [comment]
@beyhan @jochenehret @AP-Hunt I believe the releases are good to go now, and should be auto-released everytime there is a cflinuxfs4 release, so I'm closing this out. Let us know if you run into any issues
